### ISSUE TITLE
Unsuccessful attempts

### ISSUE THREAD

**Issue by polmoneys** [mars/heroku-nextjs#2]
aloha, my app has a Component folder besides Page and when following the Readme I get this error.

![Error Scren](https://cloud.githubusercontent.com/assets/7026863/20309791/b203ac20-ab49-11e6-9810-afa3004cc31e.png)

looks like it's looking for the Component files inside Page folder/directory ? this is my first deployment experience with next.js and heroku so my noob-ness may be the problem...any pointers ? 

TIA

**Comment by mars** [comment]
Hi @polmoneys,

Based on your description of the problem and the error backtrace, I suspect that the folder is named "Components" while the code references `../components`.

The Linux filesystem used on Heroku is case-sensitive, which means differently capitalized file names are discerned as different files. On Mac & Windows computers this is not the case; case differences are ignored.

This can be a confusing problem for sure. To fix, either change your code reference to match the file name or use `git mv Components components && git commit components` to rename.

**Comment by polmoneys** [comment]
Thanks @mars for your input. This is how my project looks like (all lowercase):

![artboard](https://cloud.githubusercontent.com/assets/7026863/20313490/687949b2-ab57-11e6-9196-5b39dc4e9038.png)

This line is the one that confuses me the most as it shouldn't be looking inside the page folder for the components :( 

![artboard2](https://cloud.githubusercontent.com/assets/7026863/20313632/ce330662-ab57-11e6-8da3-3b2a51d283c1.png)

**Comment by mars** [comment]
I just tested [adding a logo component](https://github.com/mars/heroku-nextjs/blob/master/pages/index.js#L4) like you describe; verified that the new component builds and renders correctly in the [demo app](https://nextjs.herokuapp.com/). So, nothing seems inherently broken with the Heroku Next.js deployment.

Your **Module not found** error does show the `../` prefix on the component path, which makes it ascend to the directory level above `pages/` before descending into `components/`. All of that looks okay to me.

Another high-level question: what does `git status` show for the repo? My next guess is that the `components` directory or some part of it has not been added & committed with git. So while it works locally, it's not actually getting deployed to Heroku since it's not all in git.

**Comment by mars** [comment]
If this problem is still unresolved, feel free to add me as a collaborator on your repo at Github so that I can diagnose directly.

**Comment by polmoneys** [comment]
added, heroku logs are as follows 

![logs](https://cloud.githubusercontent.com/assets/7026863/20316651/f5abedb6-ab62-11e6-870d-d405910e2fe1.png)

**Comment by mars** [comment]
I checked out the source in your Github repo, and found that capitalization is the problem:

``` javascript
import Sprite from '../components/icons/sprite';
```

…but the actual file name is capitalized `Sprite`.

Simplest fix is to change the `import` to reference the capitalized file name.

**Comment by polmoneys** [comment]
I don't understand how on my finder/atom it's lowercase but on github appears capitalised :S

![artboard 2](https://cloud.githubusercontent.com/assets/7026863/20319388/222b083a-ab6e-11e6-88ca-843a60580006.png)

Anyway, this is clearly not an issue with heroku-nextjs but me. I'll close and keep investigating...**muchas gracias** for the gift of your time !

**Comment by mars** [comment]
Case-sensitivity differences between computers is confounding.

My solution is:

> Always create lowercase file names,  
> & never change the case of a committed file name.

Of course those rules can be broken if you use `git mv … && git commit .` to rename things later (not the operating system's rename or move command.)

Good luck with your app🚀
