### ISSUE TITLE
Deoptimization with Next's runtime config

### ISSUE THREAD

**Issue by lifeiscontent** [mars/heroku-nextjs#51]
@mars one thing I've realized is when you use a runtime config in next.js there's actually a significant performance cost, I noticed you created a inner build pack for create-react-app that injects the env.

is there a demo using that buildpack in next.js? if you set all of your env vars in next.js under the env key, they get statically compiled into the JS assets, but in heroku, if you promote from staging to production, the env vars are hard coded into the JS assets at that point so if you change a endpoint to some database somewhere, you'll probably still be using the staging endpoint.

would love to hear your thoughts on how to solve this issue.

**Comment by mars** [comment]
> a significant performance cost

My understanding based on the [Next.js Runtime config docs](https://nextjs.org/docs/#runtime-configuration) is that it will make the page render server-side for each request, which is the same de-optimization that happens if you use `getInitialProps`… Next can only pre-render "static" pages that don't have runtime data dependencies.

This is this de-optimization you're trying to avoid?

If that's the case, you probably could use the technique for create-react-app-buildpack by following the [Runtime Config steps on the CRA + Node.js repo](https://github.com/mars/heroku-cra-node#user-content-runtime-config). Looks like the bundle location for injection would need to be set to:

```
JS_RUNTIME_TARGET_BUNDLE=/app/.next/static/chunks/*.js
```

Let me know how it goes! Hopefully it just works :)

**Comment by lifeiscontent** [comment]
@mars would I just need to include the inner buildpack or both?

**Comment by mars** [comment]
As Step 1 in the [linked "Runtime Config steps"](https://github.com/mars/heroku-cra-node#user-content-runtime-config) says:

1. Add the inner buildpack to your app, so that the `heroku/nodejs` buildpack is last:

   ```
   heroku buildpacks:add -i 1 https://github.com/mars/create-react-app-inner-buildpack
   
   # Verify that create-react-app-inner-buildpack comes before nodejs
   heroku buildpacks
   ```

Make sure you follow those instructions completely 🙏

**Comment by lifeiscontent** [comment]
@mars so I followed the instructions, it looks like there might be another step required because the same app is still running. if you have some time, I can add you to the heroku example apps I've got running to save you time from setting up a project, or if you have any other tips on what it might be please share, as I'm sure you've got a lot more knowledge/context in terms of how these things play together

**Comment by mars** [comment]
I'm attempting this myself now and will report back progress.

To confirm, did you:

1. migrate the app over to read variables through the [runtime config npm package](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-runtime-configuration)? (as documented in **create-react-app-buildpack**)
2. add **create-react-app-inner-buildpack** to the Heroku app?

**Comment by lifeiscontent** [comment]
@mars oh, I didn't know that was a thing, let me try it out, and I'll report back. for next.js would you use this package directly in the components that need the config, or the next.config.js somewhere?

**Comment by lifeiscontent** [comment]
@mars I've tried following the exact setup from the example but I'm getting this error on build:

```
Runtime env vars cannot be parsed. Content is `{{REACT_APP_VARS_AS_JSON_______…`
```

**Comment by mars** [comment]
So, this technique is not going to apply cleanly to Next.js, if at all.

Using that package locally, `npm run dev` spits out this error:

```
`process.env` is not defined. Compile-time environment will be empty.
```

…which means Next's own config system is in control 🎛 

As I've dug deeper into this, it looks like that the static-rendered optimization happens at build time, so no `Page` Javascript executes at runtime. Pretty flippin' cool.

As far as I can tell, that static pre-rendering means it is unlikely that the bundle injection technique from create-react-app-buildpack will work for Next.

*Runtime* variables need to be changeable after *build*, so Next de-optimizes, so that it can render with the fresh *runtime* values.

I don't advise hacking this to make it work. Either:

* use compile-time vars and rebuild for each new deployment, or
* use runtime vars and take the performance hit of server render per request.

I suggest hopping over to the Next.js GitHub issues to talk to them about this `process.env` -based Runtime config NOT de-optimize, because those environment variables do not change during the lifetime of a process. Maybe there's already an issue…

**Comment by lifeiscontent** [comment]
@mars I just want to say thank you for spending some time on this, and how incredibly fast you were at responding. 🍻 

Have a wonderful week! 👍

**Comment by lifeiscontent** [comment]
@mars just as a follow up, when promoting from staging to production the build wouldn't be run, is there a way to disable this step or force it to run a build during the promotion step? otherwise the API url I have for the backend server will be hard coded to staging when promoting.

the only real way I've been able to achieve this is to skip the build step, create a Procfile and in the `web` process run `yarn build && yarn start`
